<h2>Datojen yhdistely vierekkäin ja allekkain</h2>

Vierekkäin yhdistettävissä datoissa täytyy molemmissa olla indeksi, jonka arvojen perusteella rivit laitetaan kohdakkain.

Allekkain yhdistettävissä datoissa täytyy olla saman nimiset muuttujat.

In [1]:
# Data-analytiikan peruskirjaston tuonti
import pandas as pd

# Varmistetaan, että kaikki datan rivit näytetään tulosteissa
pd.set_option('display.max_rows', 100)

# Datojen avaaminen dataframeihin
df1 = pd.read_excel('http://taanila.fi/data1.xlsx')
df2 = pd.read_excel('http://taanila.fi/data1_s.xlsx')

In [2]:
# Data, johon yhdistetään sairaspoissaolot
df1

,nro,sukup,ikä,perhe,koulutus,palveluv,palkka,johto,työtov,työymp,palkkat,työteht,työterv,lomaosa,kuntosa,hieroja
0,1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3,NaN,NaN,NaN,NaN
1,2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3,NaN,NaN,NaN,NaN
2,3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3,1.0,NaN,NaN,NaN
3,4,1,36,2,1.0,14.0,2144,3,3.0,3,3,3,1.0,NaN,NaN,NaN
4,5,1,24,1,2.0,4.0,2183,2,3.0,2,1,2,1.0,NaN,NaN,NaN
5,6,2,31,2,2.0,14.0,1910,4,4.0,5,2,4,1.0,1.0,NaN,NaN
6,7,1,49,1,2.0,16.0,2066,3,5.0,4,2,2,NaN,NaN,1.0,NaN
7,8,1,55,1,1.0,0.0,2066,3,5.0,3,1,3,1.0,NaN,NaN,NaN
8,9,1,40,2,1.0,23.0,2768,2,4.0,4,2,4,NaN,1.0,NaN,NaN
9,10,1,33,1,1.0,16.0,2106,3,2.0,1,1,1,1.0,NaN,NaN,NaN
10,11,1,39,2,1.0,22.0,2651,3,5.0,3,1,3,NaN,NaN,NaN,NaN
11,12,1,40,2,3.0,21.0,2846,3,5.0,3,1,2,NaN,1.0,NaN,1.0
12,13,1,35,2,3.0,15.0,2808,3,5.0,3,1,4,NaN,1.0,NaN,NaN
13,14,1,58,2,3.0,21.0,3587,4,5.0,4,1,3,NaN,NaN,NaN,NaN
14,15,1,53,2,3.0,12.0,3393,4,4.0,4,4,4,NaN,1.0,NaN,NaN
15,16,2,42,2,3.0,23.0,2691,3,3.0,3,3,3,1.0,NaN,NaN,1.0
16,17,1,26,1,4.0,2.0,5225,5,5.0,5,4,5,NaN,NaN,1.0,NaN
17,18,2,38,2,3.0,17.0,2729,4,3.0,4,2,1,NaN,NaN,NaN,NaN
18,19,1,42,1,3.0,20.0,2925,2,3.0,4,1,4,1.0,NaN,NaN,1.0
19,20,2,40,2,2.0,13.0,2457,3,3.0,4,3,2,1.0,NaN,NaN,1.0
20,21,2,40,2,3.0,20.0,2691,2,4.0,5,3,4,NaN,NaN,NaN,NaN
21,22,1,47,2,3.0,17.0,4874,2,4.0,3,2,4,NaN,1.0,NaN,NaN
22,23,1,44,2,1.0,27.0,3510,4,4.0,4,4,4,NaN,1.0,NaN,NaN
23,24,1,36,1,3.0,7.0,4446,3,4.0,3,4,5,NaN,NaN,NaN,NaN
24,25,1,43,2,3.0,1.0,2925,4,4.0,4,4,4,NaN,1.0,NaN,NaN
25,26,1,26,1,2.0,3.0,1521,2,4.0,2,1,3,1.0,NaN,1.0,1.0
26,27,1,26,1,2.0,2.0,1989,2,4.0,2,2,3,1.0,NaN,NaN,1.0
27,28,2,56,1,1.0,15.0,2223,3,4.0,3,2,4,1.0,NaN,NaN,1.0
28,29,1,47,2,2.0,23.0,2808,2,4.0,3,1,4,1.0,NaN,NaN,NaN
29,30,1,21,1,NaN,NaN,1949,4,4.0,3,3,2,1.0,NaN,NaN,NaN
30,31,1,21,1,3.0,1.0,2340,4,5.0,3,4,2,1.0,NaN,1.0,1.0
31,32,1,45,2,1.0,24.0,2925,4,4.0,4,3,4,NaN,1.0,NaN,NaN
32,33,1,59,2,3.0,15.0,6278,4,4.0,5,4,4,NaN,1.0,NaN,NaN
33,34,1,37,2,1.0,14.0,2183,1,5.0,1,1,2,1.0,NaN,NaN,1.0
34,35,1,28,2,2.0,5.0,1989,3,4.0,3,3,3,1.0,NaN,1.0,1.0
35,36,1,31,2,3.0,0.0,1559,2,4.0,3,1,3,1.0,NaN,NaN,NaN
36,37,2,56,2,2.0,17.0,2729,5,5.0,5,5,5,NaN,NaN,NaN,1.0
37,38,1,50,2,1.0,1.0,2027,5,5.0,4,1,4,1.0,1.0,NaN,NaN
38,39,1,30,1,2.0,10.0,2300,3,5.0,3,3,4,NaN,NaN,NaN,NaN
39,40,1,32,1,1.0,3.0,2106,1,5.0,4,1,3,1.0,NaN,NaN,NaN
40,41,1,33,2,3.0,9.0,2846,3,3.0,4,2,3,1.0,NaN,NaN,NaN
41,42,1,29,1,2.0,6.0,2534,3,4.0,3,1,2,1.0,NaN,NaN,NaN
42,43,2,40,2,3.0,12.0,2144,4,4.0,4,4,4,NaN,1.0,NaN,NaN
43,44,1,30,1,2.0,7.0,2223,2,3.0,4,1,3,1.0,NaN,NaN,1.0
44,45,1,55,2,1.0,35.0,2651,4,5.0,4,2,4,1.0,NaN,NaN,1.0
45,46,2,51,2,1.0,28.0,1989,3,3.0,2,2,3,1.0,NaN,NaN,1.0
46,47,2,22,1,3.0,21.0,1872,3,3.0,4,1,3,NaN,NaN,1.0,NaN
47,48,1,34,2,1.0,18.0,2183,4,5.0,4,1,3,NaN,NaN,NaN,NaN
48,49,1,27,2,2.0,7.0,2729,4,4.0,3,3,5,NaN,NaN,1.0,NaN
49,50,1,29,1,3.0,7.0,2340,3,4.0,3,2,3,1.0,NaN,NaN,NaN
50,51,2,39,2,2.0,10.0,2106,4,5.0,5,4,5,NaN,1.0,NaN,NaN
51,52,1,41,2,1.0,18.0,2261,5,5.0,5,2,5,NaN,1.0,NaN,NaN
52,53,1,44,2,1.0,3.0,1989,1,2.0,2,1,1,1.0,NaN,NaN,NaN
53,54,1,25,1,2.0,1.0,1559,2,4.0,3,1,2,1.0,NaN,NaN,NaN
54,55,2,45,2,1.0,17.0,2417,3,5.0,4,3,3,NaN,NaN,NaN,1.0
55,56,2,31,2,1.0,6.0,1949,4,4.0,4,3,3,1.0,NaN,NaN,1.0
56,57,1,61,2,2.0,36.0,3119,2,NaN,2,1,5,1.0,NaN,NaN,1.0
57,58,1,38,2,2.0,NaN,2574,2,3.0,1,1,2,1.0,NaN,NaN,1.0
58,59,1,20,1,2.0,1.0,2261,3,4.0,3,2,3,NaN,NaN,NaN,NaN
59,60,1,31,1,1.0,10.0,2144,4,4.0,3,1,3,1.0,NaN,NaN,NaN
60,61,1,44,1,1.0,19.0,2183,2,2.0,1,1,2,1.0,NaN,NaN,NaN
61,62,1,40,2,1.0,0.0,1872,2,3.0,1,2,3,1.0,NaN,NaN,NaN
62,63,2,51,2,2.0,10.0,1872,4,3.0,2,2,3,1.0,NaN,NaN,NaN
63,64,2,44,1,2.0,1.0,1715,4,4.0,3,2,3,1.0,NaN,NaN,1.0
64,65,2,35,2,2.0,17.0,2691,4,4.0,5,2,4,1.0,NaN,NaN,1.0
65,66,2,37,2,1.0,16.0,2027,5,5.0,5,4,5,1.0,1.0,NaN,NaN
66,67,1,37,2,4.0,8.0,5069,3,4.0,3,2,2,1.0,1.0,NaN,1.0
67,68,1,33,2,3.0,7.0,2417,2,4.0,3,1,4,NaN,NaN,NaN,NaN
68,69,1,28,2,2.0,1.0,3510,4,5.0,3,1,4,NaN,NaN,NaN,NaN
69,70,1,52,2,2.0,22.0,3119,3,4.0,3,2,2,1.0,1.0,NaN,1.0
70,71,1,34,2,2.0,1.0,2495,3,5.0,5,3,4,NaN,1.0,NaN,NaN
71,72,1,46,2,2.0,23.0,3470,3,5.0,5,3,4,NaN,1.0,NaN,NaN
72,73,2,40,2,3.0,2.0,2027,5,3.0,4,3,4,1.0,NaN,NaN,NaN
73,74,1,45,2,1.0,20.0,2846,3,5.0,1,1,3,1.0,NaN,NaN,NaN
74,75,1,40,1,1.0,1.0,1949,1,5.0,1,1,1,1.0,NaN,NaN,NaN
75,76,1,37,1,2.0,15.0,1598,1,5.0,1,1,1,1.0,NaN,NaN,NaN
76,77,1,39,1,2.0,22.0,2183,4,5.0,3,1,2,NaN,NaN,NaN,NaN
77,78,1,22,1,3.0,0.0,1598,4,4.0,4,3,4,NaN,1.0,1.0,NaN
78,79,1,33,1,1.0,2.0,1638,1,3.0,2,1,2,1.0,NaN,NaN,NaN
79,80,1,27,1,2.0,7.0,2612,3,4.0,3,3,3,1.0,NaN,1.0,NaN
80,81,1,35,2,2.0,16.0,2808,3,4.0,3,3,3,NaN,NaN,NaN,NaN
81,82,2,35,2,3.0,15.0,2183,3,4.0,4,3,4,1.0,NaN,NaN,NaN

In [3]:
# Sairaspoissaolot
# nro-sarakkeen tiedot vastaavat toisiaan: esim. nro 6 vastaa henkilöä, jonka nro on 6 myös df1:ssä
df2

   nro  sairaspoissaolot
0    6                20
1    7                 1
2    8                 7
3   45                 5
4   46                 4
5   47                 2
6   48                 0
7   49                 5
8   50                 0

In [4]:
# Siirretään nro indeksiksi
df1 = df1.set_index('nro')
df2 = df2.set_index('nro')

In [5]:
# Varmistetaan, että nro:n siirto indeksiksi onnnistui
df1

,sukup,ikä,perhe,koulutus,palveluv,palkka,johto,työtov,työymp,palkkat,työteht,työterv,lomaosa,kuntosa,hieroja
nro,,,,,,,,,,,,,,,
1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3,NaN,NaN,NaN,NaN
2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3,NaN,NaN,NaN,NaN
3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3,1.0,NaN,NaN,NaN
4,1,36,2,1.0,14.0,2144,3,3.0,3,3,3,1.0,NaN,NaN,NaN
5,1,24,1,2.0,4.0,2183,2,3.0,2,1,2,1.0,NaN,NaN,NaN
6,2,31,2,2.0,14.0,1910,4,4.0,5,2,4,1.0,1.0,NaN,NaN
7,1,49,1,2.0,16.0,2066,3,5.0,4,2,2,NaN,NaN,1.0,NaN
8,1,55,1,1.0,0.0,2066,3,5.0,3,1,3,1.0,NaN,NaN,NaN
9,1,40,2,1.0,23.0,2768,2,4.0,4,2,4,NaN,1.0,NaN,NaN
10,1,33,1,1.0,16.0,2106,3,2.0,1,1,1,1.0,NaN,NaN,NaN
11,1,39,2,1.0,22.0,2651,3,5.0,3,1,3,NaN,NaN,NaN,NaN
12,1,40,2,3.0,21.0,2846,3,5.0,3,1,2,NaN,1.0,NaN,1.0
13,1,35,2,3.0,15.0,2808,3,5.0,3,1,4,NaN,1.0,NaN,NaN
14,1,58,2,3.0,21.0,3587,4,5.0,4,1,3,NaN,NaN,NaN,NaN
15,1,53,2,3.0,12.0,3393,4,4.0,4,4,4,NaN,1.0,NaN,NaN
16,2,42,2,3.0,23.0,2691,3,3.0,3,3,3,1.0,NaN,NaN,1.0
17,1,26,1,4.0,2.0,5225,5,5.0,5,4,5,NaN,NaN,1.0,NaN
18,2,38,2,3.0,17.0,2729,4,3.0,4,2,1,NaN,NaN,NaN,NaN
19,1,42,1,3.0,20.0,2925,2,3.0,4,1,4,1.0,NaN,NaN,1.0
20,2,40,2,2.0,13.0,2457,3,3.0,4,3,2,1.0,NaN,NaN,1.0
21,2,40,2,3.0,20.0,2691,2,4.0,5,3,4,NaN,NaN,NaN,NaN
22,1,47,2,3.0,17.0,4874,2,4.0,3,2,4,NaN,1.0,NaN,NaN
23,1,44,2,1.0,27.0,3510,4,4.0,4,4,4,NaN,1.0,NaN,NaN
24,1,36,1,3.0,7.0,4446,3,4.0,3,4,5,NaN,NaN,NaN,NaN
25,1,43,2,3.0,1.0,2925,4,4.0,4,4,4,NaN,1.0,NaN,NaN
26,1,26,1,2.0,3.0,1521,2,4.0,2,1,3,1.0,NaN,1.0,1.0
27,1,26,1,2.0,2.0,1989,2,4.0,2,2,3,1.0,NaN,NaN,1.0
28,2,56,1,1.0,15.0,2223,3,4.0,3,2,4,1.0,NaN,NaN,1.0
29,1,47,2,2.0,23.0,2808,2,4.0,3,1,4,1.0,NaN,NaN,NaN
30,1,21,1,NaN,NaN,1949,4,4.0,3,3,2,1.0,NaN,NaN,NaN
31,1,21,1,3.0,1.0,2340,4,5.0,3,4,2,1.0,NaN,1.0,1.0
32,1,45,2,1.0,24.0,2925,4,4.0,4,3,4,NaN,1.0,NaN,NaN
33,1,59,2,3.0,15.0,6278,4,4.0,5,4,4,NaN,1.0,NaN,NaN
34,1,37,2,1.0,14.0,2183,1,5.0,1,1,2,1.0,NaN,NaN,1.0
35,1,28,2,2.0,5.0,1989,3,4.0,3,3,3,1.0,NaN,1.0,1.0
36,1,31,2,3.0,0.0,1559,2,4.0,3,1,3,1.0,NaN,NaN,NaN
37,2,56,2,2.0,17.0,2729,5,5.0,5,5,5,NaN,NaN,NaN,1.0
38,1,50,2,1.0,1.0,2027,5,5.0,4,1,4,1.0,1.0,NaN,NaN
39,1,30,1,2.0,10.0,2300,3,5.0,3,3,4,NaN,NaN,NaN,NaN
40,1,32,1,1.0,3.0,2106,1,5.0,4,1,3,1.0,NaN,NaN,NaN
41,1,33,2,3.0,9.0,2846,3,3.0,4,2,3,1.0,NaN,NaN,NaN
42,1,29,1,2.0,6.0,2534,3,4.0,3,1,2,1.0,NaN,NaN,NaN
43,2,40,2,3.0,12.0,2144,4,4.0,4,4,4,NaN,1.0,NaN,NaN
44,1,30,1,2.0,7.0,2223,2,3.0,4,1,3,1.0,NaN,NaN,1.0
45,1,55,2,1.0,35.0,2651,4,5.0,4,2,4,1.0,NaN,NaN,1.0
46,2,51,2,1.0,28.0,1989,3,3.0,2,2,3,1.0,NaN,NaN,1.0
47,2,22,1,3.0,21.0,1872,3,3.0,4,1,3,NaN,NaN,1.0,NaN
48,1,34,2,1.0,18.0,2183,4,5.0,4,1,3,NaN,NaN,NaN,NaN
49,1,27,2,2.0,7.0,2729,4,4.0,3,3,5,NaN,NaN,1.0,NaN
50,1,29,1,3.0,7.0,2340,3,4.0,3,2,3,1.0,NaN,NaN,NaN
51,2,39,2,2.0,10.0,2106,4,5.0,5,4,5,NaN,1.0,NaN,NaN
52,1,41,2,1.0,18.0,2261,5,5.0,5,2,5,NaN,1.0,NaN,NaN
53,1,44,2,1.0,3.0,1989,1,2.0,2,1,1,1.0,NaN,NaN,NaN
54,1,25,1,2.0,1.0,1559,2,4.0,3,1,2,1.0,NaN,NaN,NaN
55,2,45,2,1.0,17.0,2417,3,5.0,4,3,3,NaN,NaN,NaN,1.0
56,2,31,2,1.0,6.0,1949,4,4.0,4,3,3,1.0,NaN,NaN,1.0
57,1,61,2,2.0,36.0,3119,2,NaN,2,1,5,1.0,NaN,NaN,1.0
58,1,38,2,2.0,NaN,2574,2,3.0,1,1,2,1.0,NaN,NaN,1.0
59,1,20,1,2.0,1.0,2261,3,4.0,3,2,3,NaN,NaN,NaN,NaN
60,1,31,1,1.0,10.0,2144,4,4.0,3,1,3,1.0,NaN,NaN,NaN
61,1,44,1,1.0,19.0,2183,2,2.0,1,1,2,1.0,NaN,NaN,NaN
62,1,40,2,1.0,0.0,1872,2,3.0,1,2,3,1.0,NaN,NaN,NaN
63,2,51,2,2.0,10.0,1872,4,3.0,2,2,3,1.0,NaN,NaN,NaN
64,2,44,1,2.0,1.0,1715,4,4.0,3,2,3,1.0,NaN,NaN,1.0
65,2,35,2,2.0,17.0,2691,4,4.0,5,2,4,1.0,NaN,NaN,1.0
66,2,37,2,1.0,16.0,2027,5,5.0,5,4,5,1.0,1.0,NaN,NaN
67,1,37,2,4.0,8.0,5069,3,4.0,3,2,2,1.0,1.0,NaN,1.0
68,1,33,2,3.0,7.0,2417,2,4.0,3,1,4,NaN,NaN,NaN,NaN
69,1,28,2,2.0,1.0,3510,4,5.0,3,1,4,NaN,NaN,NaN,NaN
70,1,52,2,2.0,22.0,3119,3,4.0,3,2,2,1.0,1.0,NaN,1.0
71,1,34,2,2.0,1.0,2495,3,5.0,5,3,4,NaN,1.0,NaN,NaN
72,1,46,2,2.0,23.0,3470,3,5.0,5,3,4,NaN,1.0,NaN,NaN
73,2,40,2,3.0,2.0,2027,5,3.0,4,3,4,1.0,NaN,NaN,NaN
74,1,45,2,1.0,20.0,2846,3,5.0,1,1,3,1.0,NaN,NaN,NaN
75,1,40,1,1.0,1.0,1949,1,5.0,1,1,1,1.0,NaN,NaN,NaN
76,1,37,1,2.0,15.0,1598,1,5.0,1,1,1,1.0,NaN,NaN,NaN
77,1,39,1,2.0,22.0,2183,4,5.0,3,1,2,NaN,NaN,NaN,NaN
78,1,22,1,3.0,0.0,1598,4,4.0,4,3,4,NaN,1.0,1.0,NaN
79,1,33,1,1.0,2.0,1638,1,3.0,2,1,2,1.0,NaN,NaN,NaN
80,1,27,1,2.0,7.0,2612,3,4.0,3,3,3,1.0,NaN,1.0,NaN
81,1,35,2,2.0,16.0,2808,3,4.0,3,3,3,NaN,NaN,NaN,NaN
82,2,35,2,3.0,15.0,2183,3,4.0,4,3,4,1.0,NaN,NaN,NaN

In [6]:
# Varmistetaan, että nro:n siirto indeksiksi onnnistui
df2

     sairaspoissaolot
nro
6                  20
7                   1
8                   7
45                  5
46                  4
47                  2
48                  0
49                  5
50                  0

In [7]:
# Yhdistetään df1 ja df2 vierekkäin (axis=1 tarkoittaa vierekkäin yhdistämistä)
df3 = pd.concat([df1, df2], axis=1)

In [8]:
# Varmistetaan yhdistämisen onnistuminen 
df3

,sukup,ikä,perhe,koulutus,palveluv,palkka,johto,työtov,työymp,palkkat,työteht,työterv,lomaosa,kuntosa,hieroja,sairaspoissaolot
nro,,,,,,,,,,,,,,,,
1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3,NaN,NaN,NaN,NaN,NaN
2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3,NaN,NaN,NaN,NaN,NaN
3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3,1.0,NaN,NaN,NaN,NaN
4,1,36,2,1.0,14.0,2144,3,3.0,3,3,3,1.0,NaN,NaN,NaN,NaN
5,1,24,1,2.0,4.0,2183,2,3.0,2,1,2,1.0,NaN,NaN,NaN,NaN
6,2,31,2,2.0,14.0,1910,4,4.0,5,2,4,1.0,1.0,NaN,NaN,20.0
7,1,49,1,2.0,16.0,2066,3,5.0,4,2,2,NaN,NaN,1.0,NaN,1.0
8,1,55,1,1.0,0.0,2066,3,5.0,3,1,3,1.0,NaN,NaN,NaN,7.0
9,1,40,2,1.0,23.0,2768,2,4.0,4,2,4,NaN,1.0,NaN,NaN,NaN
10,1,33,1,1.0,16.0,2106,3,2.0,1,1,1,1.0,NaN,NaN,NaN,NaN
11,1,39,2,1.0,22.0,2651,3,5.0,3,1,3,NaN,NaN,NaN,NaN,NaN
12,1,40,2,3.0,21.0,2846,3,5.0,3,1,2,NaN,1.0,NaN,1.0,NaN
13,1,35,2,3.0,15.0,2808,3,5.0,3,1,4,NaN,1.0,NaN,NaN,NaN
14,1,58,2,3.0,21.0,3587,4,5.0,4,1,3,NaN,NaN,NaN,NaN,NaN
15,1,53,2,3.0,12.0,3393,4,4.0,4,4,4,NaN,1.0,NaN,NaN,NaN
16,2,42,2,3.0,23.0,2691,3,3.0,3,3,3,1.0,NaN,NaN,1.0,NaN
17,1,26,1,4.0,2.0,5225,5,5.0,5,4,5,NaN,NaN,1.0,NaN,NaN
18,2,38,2,3.0,17.0,2729,4,3.0,4,2,1,NaN,NaN,NaN,NaN,NaN
19,1,42,1,3.0,20.0,2925,2,3.0,4,1,4,1.0,NaN,NaN,1.0,NaN
20,2,40,2,2.0,13.0,2457,3,3.0,4,3,2,1.0,NaN,NaN,1.0,NaN
21,2,40,2,3.0,20.0,2691,2,4.0,5,3,4,NaN,NaN,NaN,NaN,NaN
22,1,47,2,3.0,17.0,4874,2,4.0,3,2,4,NaN,1.0,NaN,NaN,NaN
23,1,44,2,1.0,27.0,3510,4,4.0,4,4,4,NaN,1.0,NaN,NaN,NaN
24,1,36,1,3.0,7.0,4446,3,4.0,3,4,5,NaN,NaN,NaN,NaN,NaN
25,1,43,2,3.0,1.0,2925,4,4.0,4,4,4,NaN,1.0,NaN,NaN,NaN
26,1,26,1,2.0,3.0,1521,2,4.0,2,1,3,1.0,NaN,1.0,1.0,NaN
27,1,26,1,2.0,2.0,1989,2,4.0,2,2,3,1.0,NaN,NaN,1.0,NaN
28,2,56,1,1.0,15.0,2223,3,4.0,3,2,4,1.0,NaN,NaN,1.0,NaN
29,1,47,2,2.0,23.0,2808,2,4.0,3,1,4,1.0,NaN,NaN,NaN,NaN
30,1,21,1,NaN,NaN,1949,4,4.0,3,3,2,1.0,NaN,NaN,NaN,NaN
31,1,21,1,3.0,1.0,2340,4,5.0,3,4,2,1.0,NaN,1.0,1.0,NaN
32,1,45,2,1.0,24.0,2925,4,4.0,4,3,4,NaN,1.0,NaN,NaN,NaN
33,1,59,2,3.0,15.0,6278,4,4.0,5,4,4,NaN,1.0,NaN,NaN,NaN
34,1,37,2,1.0,14.0,2183,1,5.0,1,1,2,1.0,NaN,NaN,1.0,NaN
35,1,28,2,2.0,5.0,1989,3,4.0,3,3,3,1.0,NaN,1.0,1.0,NaN
36,1,31,2,3.0,0.0,1559,2,4.0,3,1,3,1.0,NaN,NaN,NaN,NaN
37,2,56,2,2.0,17.0,2729,5,5.0,5,5,5,NaN,NaN,NaN,1.0,NaN
38,1,50,2,1.0,1.0,2027,5,5.0,4,1,4,1.0,1.0,NaN,NaN,NaN
39,1,30,1,2.0,10.0,2300,3,5.0,3,3,4,NaN,NaN,NaN,NaN,NaN
40,1,32,1,1.0,3.0,2106,1,5.0,4,1,3,1.0,NaN,NaN,NaN,NaN
41,1,33,2,3.0,9.0,2846,3,3.0,4,2,3,1.0,NaN,NaN,NaN,NaN
42,1,29,1,2.0,6.0,2534,3,4.0,3,1,2,1.0,NaN,NaN,NaN,NaN
43,2,40,2,3.0,12.0,2144,4,4.0,4,4,4,NaN,1.0,NaN,NaN,NaN
44,1,30,1,2.0,7.0,2223,2,3.0,4,1,3,1.0,NaN,NaN,1.0,NaN
45,1,55,2,1.0,35.0,2651,4,5.0,4,2,4,1.0,NaN,NaN,1.0,5.0
46,2,51,2,1.0,28.0,1989,3,3.0,2,2,3,1.0,NaN,NaN,1.0,4.0
47,2,22,1,3.0,21.0,1872,3,3.0,4,1,3,NaN,NaN,1.0,NaN,2.0
48,1,34,2,1.0,18.0,2183,4,5.0,4,1,3,NaN,NaN,NaN,NaN,0.0
49,1,27,2,2.0,7.0,2729,4,4.0,3,3,5,NaN,NaN,1.0,NaN,5.0
50,1,29,1,3.0,7.0,2340,3,4.0,3,2,3,1.0,NaN,NaN,NaN,0.0
51,2,39,2,2.0,10.0,2106,4,5.0,5,4,5,NaN,1.0,NaN,NaN,NaN
52,1,41,2,1.0,18.0,2261,5,5.0,5,2,5,NaN,1.0,NaN,NaN,NaN
53,1,44,2,1.0,3.0,1989,1,2.0,2,1,1,1.0,NaN,NaN,NaN,NaN
54,1,25,1,2.0,1.0,1559,2,4.0,3,1,2,1.0,NaN,NaN,NaN,NaN
55,2,45,2,1.0,17.0,2417,3,5.0,4,3,3,NaN,NaN,NaN,1.0,NaN
56,2,31,2,1.0,6.0,1949,4,4.0,4,3,3,1.0,NaN,NaN,1.0,NaN
57,1,61,2,2.0,36.0,3119,2,NaN,2,1,5,1.0,NaN,NaN,1.0,NaN
58,1,38,2,2.0,NaN,2574,2,3.0,1,1,2,1.0,NaN,NaN,1.0,NaN
59,1,20,1,2.0,1.0,2261,3,4.0,3,2,3,NaN,NaN,NaN,NaN,NaN
60,1,31,1,1.0,10.0,2144,4,4.0,3,1,3,1.0,NaN,NaN,NaN,NaN
61,1,44,1,1.0,19.0,2183,2,2.0,1,1,2,1.0,NaN,NaN,NaN,NaN
62,1,40,2,1.0,0.0,1872,2,3.0,1,2,3,1.0,NaN,NaN,NaN,NaN
63,2,51,2,2.0,10.0,1872,4,3.0,2,2,3,1.0,NaN,NaN,NaN,NaN
64,2,44,1,2.0,1.0,1715,4,4.0,3,2,3,1.0,NaN,NaN,1.0,NaN
65,2,35,2,2.0,17.0,2691,4,4.0,5,2,4,1.0,NaN,NaN,1.0,NaN
66,2,37,2,1.0,16.0,2027,5,5.0,5,4,5,1.0,1.0,NaN,NaN,NaN
67,1,37,2,4.0,8.0,5069,3,4.0,3,2,2,1.0,1.0,NaN,1.0,NaN
68,1,33,2,3.0,7.0,2417,2,4.0,3,1,4,NaN,NaN,NaN,NaN,NaN
69,1,28,2,2.0,1.0,3510,4,5.0,3,1,4,NaN,NaN,NaN,NaN,NaN
70,1,52,2,2.0,22.0,3119,3,4.0,3,2,2,1.0,1.0,NaN,1.0,NaN
71,1,34,2,2.0,1.0,2495,3,5.0,5,3,4,NaN,1.0,NaN,NaN,NaN
72,1,46,2,2.0,23.0,3470,3,5.0,5,3,4,NaN,1.0,NaN,NaN,NaN
73,2,40,2,3.0,2.0,2027,5,3.0,4,3,4,1.0,NaN,NaN,NaN,NaN
74,1,45,2,1.0,20.0,2846,3,5.0,1,1,3,1.0,NaN,NaN,NaN,NaN
75,1,40,1,1.0,1.0,1949,1,5.0,1,1,1,1.0,NaN,NaN,NaN,NaN
76,1,37,1,2.0,15.0,1598,1,5.0,1,1,1,1.0,NaN,NaN,NaN,NaN
77,1,39,1,2.0,22.0,2183,4,5.0,3,1,2,NaN,NaN,NaN,NaN,NaN
78,1,22,1,3.0,0.0,1598,4,4.0,4,3,4,NaN,1.0,1.0,NaN,NaN
79,1,33,1,1.0,2.0,1638,1,3.0,2,1,2,1.0,NaN,NaN,NaN,NaN
80,1,27,1,2.0,7.0,2612,3,4.0,3,3,3,1.0,NaN,1.0,NaN,NaN
81,1,35,2,2.0,16.0,2808,3,4.0,3,3,3,NaN,NaN,NaN,NaN,NaN
82,2,35,2,3.0,15.0,2183,3,4.0,4,3,4,1.0,NaN,NaN,NaN,NaN

In [9]:
# data1_add.xlsx sisältää tietoja, jotka halutaan lisätä df1:een
df4 = pd.read_excel('http://taanila.fi/data1_add.xlsx')
df4 = df4.set_index('nro')
df4

,sukup,ikä,perhe,koulutus,palveluv,palkka,johto,työtov,työymp,palkkat,työteht,työterv,lomaosa,kuntosa,hieroja
nro,,,,,,,,,,,,,,,
83,2,31,2,3,1,2800,4,4,4,3,3,1,NaN,NaN,1.0
84,1,26,1,2,0,2500,5,4,3,2,5,1,NaN,NaN,NaN
85,1,32,2,2,0,2500,5,3,2,2,3,1,NaN,1.0,NaN
86,1,40,1,2,0,2500,3,4,3,2,3,1,NaN,1.0,NaN
87,1,31,1,4,1,3500,4,4,3,3,3,1,NaN,1.0,NaN
88,1,28,1,4,0,4600,4,3,2,4,2,1,NaN,NaN,NaN
89,1,29,1,4,0,3900,4,3,3,4,3,1,NaN,NaN,NaN
90,2,31,2,2,0,2400,4,3,2,2,3,1,NaN,1.0,NaN

In [10]:
# Yhdistetään df3 ja df4 allekkain
df5 = pd.concat([df3, df4], sort=False)
df5

,sukup,ikä,perhe,koulutus,palveluv,palkka,johto,työtov,työymp,palkkat,työteht,työterv,lomaosa,kuntosa,hieroja,sairaspoissaolot
nro,,,,,,,,,,,,,,,,
1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3,NaN,NaN,NaN,NaN,NaN
2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3,NaN,NaN,NaN,NaN,NaN
3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3,1.0,NaN,NaN,NaN,NaN
4,1,36,2,1.0,14.0,2144,3,3.0,3,3,3,1.0,NaN,NaN,NaN,NaN
5,1,24,1,2.0,4.0,2183,2,3.0,2,1,2,1.0,NaN,NaN,NaN,NaN
6,2,31,2,2.0,14.0,1910,4,4.0,5,2,4,1.0,1.0,NaN,NaN,20.0
7,1,49,1,2.0,16.0,2066,3,5.0,4,2,2,NaN,NaN,1.0,NaN,1.0
8,1,55,1,1.0,0.0,2066,3,5.0,3,1,3,1.0,NaN,NaN,NaN,7.0
9,1,40,2,1.0,23.0,2768,2,4.0,4,2,4,NaN,1.0,NaN,NaN,NaN
10,1,33,1,1.0,16.0,2106,3,2.0,1,1,1,1.0,NaN,NaN,NaN,NaN
11,1,39,2,1.0,22.0,2651,3,5.0,3,1,3,NaN,NaN,NaN,NaN,NaN
12,1,40,2,3.0,21.0,2846,3,5.0,3,1,2,NaN,1.0,NaN,1.0,NaN
13,1,35,2,3.0,15.0,2808,3,5.0,3,1,4,NaN,1.0,NaN,NaN,NaN
14,1,58,2,3.0,21.0,3587,4,5.0,4,1,3,NaN,NaN,NaN,NaN,NaN
15,1,53,2,3.0,12.0,3393,4,4.0,4,4,4,NaN,1.0,NaN,NaN,NaN
16,2,42,2,3.0,23.0,2691,3,3.0,3,3,3,1.0,NaN,NaN,1.0,NaN
17,1,26,1,4.0,2.0,5225,5,5.0,5,4,5,NaN,NaN,1.0,NaN,NaN
18,2,38,2,3.0,17.0,2729,4,3.0,4,2,1,NaN,NaN,NaN,NaN,NaN
19,1,42,1,3.0,20.0,2925,2,3.0,4,1,4,1.0,NaN,NaN,1.0,NaN
20,2,40,2,2.0,13.0,2457,3,3.0,4,3,2,1.0,NaN,NaN,1.0,NaN
21,2,40,2,3.0,20.0,2691,2,4.0,5,3,4,NaN,NaN,NaN,NaN,NaN
22,1,47,2,3.0,17.0,4874,2,4.0,3,2,4,NaN,1.0,NaN,NaN,NaN
23,1,44,2,1.0,27.0,3510,4,4.0,4,4,4,NaN,1.0,NaN,NaN,NaN
24,1,36,1,3.0,7.0,4446,3,4.0,3,4,5,NaN,NaN,NaN,NaN,NaN
25,1,43,2,3.0,1.0,2925,4,4.0,4,4,4,NaN,1.0,NaN,NaN,NaN
26,1,26,1,2.0,3.0,1521,2,4.0,2,1,3,1.0,NaN,1.0,1.0,NaN
27,1,26,1,2.0,2.0,1989,2,4.0,2,2,3,1.0,NaN,NaN,1.0,NaN
28,2,56,1,1.0,15.0,2223,3,4.0,3,2,4,1.0,NaN,NaN,1.0,NaN
29,1,47,2,2.0,23.0,2808,2,4.0,3,1,4,1.0,NaN,NaN,NaN,NaN
30,1,21,1,NaN,NaN,1949,4,4.0,3,3,2,1.0,NaN,NaN,NaN,NaN
31,1,21,1,3.0,1.0,2340,4,5.0,3,4,2,1.0,NaN,1.0,1.0,NaN
32,1,45,2,1.0,24.0,2925,4,4.0,4,3,4,NaN,1.0,NaN,NaN,NaN
33,1,59,2,3.0,15.0,6278,4,4.0,5,4,4,NaN,1.0,NaN,NaN,NaN
34,1,37,2,1.0,14.0,2183,1,5.0,1,1,2,1.0,NaN,NaN,1.0,NaN
35,1,28,2,2.0,5.0,1989,3,4.0,3,3,3,1.0,NaN,1.0,1.0,NaN
36,1,31,2,3.0,0.0,1559,2,4.0,3,1,3,1.0,NaN,NaN,NaN,NaN
37,2,56,2,2.0,17.0,2729,5,5.0,5,5,5,NaN,NaN,NaN,1.0,NaN
38,1,50,2,1.0,1.0,2027,5,5.0,4,1,4,1.0,1.0,NaN,NaN,NaN
39,1,30,1,2.0,10.0,2300,3,5.0,3,3,4,NaN,NaN,NaN,NaN,NaN
40,1,32,1,1.0,3.0,2106,1,5.0,4,1,3,1.0,NaN,NaN,NaN,NaN
41,1,33,2,3.0,9.0,2846,3,3.0,4,2,3,1.0,NaN,NaN,NaN,NaN
42,1,29,1,2.0,6.0,2534,3,4.0,3,1,2,1.0,NaN,NaN,NaN,NaN
43,2,40,2,3.0,12.0,2144,4,4.0,4,4,4,NaN,1.0,NaN,NaN,NaN
44,1,30,1,2.0,7.0,2223,2,3.0,4,1,3,1.0,NaN,NaN,1.0,NaN
45,1,55,2,1.0,35.0,2651,4,5.0,4,2,4,1.0,NaN,NaN,1.0,5.0
46,2,51,2,1.0,28.0,1989,3,3.0,2,2,3,1.0,NaN,NaN,1.0,4.0
47,2,22,1,3.0,21.0,1872,3,3.0,4,1,3,NaN,NaN,1.0,NaN,2.0
48,1,34,2,1.0,18.0,2183,4,5.0,4,1,3,NaN,NaN,NaN,NaN,0.0
49,1,27,2,2.0,7.0,2729,4,4.0,3,3,5,NaN,NaN,1.0,NaN,5.0
50,1,29,1,3.0,7.0,2340,3,4.0,3,2,3,1.0,NaN,NaN,NaN,0.0
51,2,39,2,2.0,10.0,2106,4,5.0,5,4,5,NaN,1.0,NaN,NaN,NaN
52,1,41,2,1.0,18.0,2261,5,5.0,5,2,5,NaN,1.0,NaN,NaN,NaN
53,1,44,2,1.0,3.0,1989,1,2.0,2,1,1,1.0,NaN,NaN,NaN,NaN
54,1,25,1,2.0,1.0,1559,2,4.0,3,1,2,1.0,NaN,NaN,NaN,NaN
55,2,45,2,1.0,17.0,2417,3,5.0,4,3,3,NaN,NaN,NaN,1.0,NaN
56,2,31,2,1.0,6.0,1949,4,4.0,4,3,3,1.0,NaN,NaN,1.0,NaN
57,1,61,2,2.0,36.0,3119,2,NaN,2,1,5,1.0,NaN,NaN,1.0,NaN
58,1,38,2,2.0,NaN,2574,2,3.0,1,1,2,1.0,NaN,NaN,1.0,NaN
59,1,20,1,2.0,1.0,2261,3,4.0,3,2,3,NaN,NaN,NaN,NaN,NaN
60,1,31,1,1.0,10.0,2144,4,4.0,3,1,3,1.0,NaN,NaN,NaN,NaN
61,1,44,1,1.0,19.0,2183,2,2.0,1,1,2,1.0,NaN,NaN,NaN,NaN
62,1,40,2,1.0,0.0,1872,2,3.0,1,2,3,1.0,NaN,NaN,NaN,NaN
63,2,51,2,2.0,10.0,1872,4,3.0,2,2,3,1.0,NaN,NaN,NaN,NaN
64,2,44,1,2.0,1.0,1715,4,4.0,3,2,3,1.0,NaN,NaN,1.0,NaN
65,2,35,2,2.0,17.0,2691,4,4.0,5,2,4,1.0,NaN,NaN,1.0,NaN
66,2,37,2,1.0,16.0,2027,5,5.0,5,4,5,1.0,1.0,NaN,NaN,NaN
67,1,37,2,4.0,8.0,5069,3,4.0,3,2,2,1.0,1.0,NaN,1.0,NaN
68,1,33,2,3.0,7.0,2417,2,4.0,3,1,4,NaN,NaN,NaN,NaN,NaN
69,1,28,2,2.0,1.0,3510,4,5.0,3,1,4,NaN,NaN,NaN,NaN,NaN
70,1,52,2,2.0,22.0,3119,3,4.0,3,2,2,1.0,1.0,NaN,1.0,NaN
71,1,34,2,2.0,1.0,2495,3,5.0,5,3,4,NaN,1.0,NaN,NaN,NaN
72,1,46,2,2.0,23.0,3470,3,5.0,5,3,4,NaN,1.0,NaN,NaN,NaN
73,2,40,2,3.0,2.0,2027,5,3.0,4,3,4,1.0,NaN,NaN,NaN,NaN
74,1,45,2,1.0,20.0,2846,3,5.0,1,1,3,1.0,NaN,NaN,NaN,NaN
75,1,40,1,1.0,1.0,1949,1,5.0,1,1,1,1.0,NaN,NaN,NaN,NaN
76,1,37,1,2.0,15.0,1598,1,5.0,1,1,1,1.0,NaN,NaN,NaN,NaN
77,1,39,1,2.0,22.0,2183,4,5.0,3,1,2,NaN,NaN,NaN,NaN,NaN
78,1,22,1,3.0,0.0,1598,4,4.0,4,3,4,NaN,1.0,1.0,NaN,NaN
79,1,33,1,1.0,2.0,1638,1,3.0,2,1,2,1.0,NaN,NaN,NaN,NaN
80,1,27,1,2.0,7.0,2612,3,4.0,3,3,3,1.0,NaN,1.0,NaN,NaN
81,1,35,2,2.0,16.0,2808,3,4.0,3,3,3,NaN,NaN,NaN,NaN,NaN
82,2,35,2,3.0,15.0,2183,3,4.0,4,3,4,1.0,NaN,NaN,NaN,NaN
83,2,31,2,3.0,1.0,2800,4,4.0,4,3,3,1.0,NaN,NaN,1.0,NaN
84,1,26,1,2.0,0.0,2500,5,4.0,3,2,5,1.0,NaN,NaN,NaN,NaN
85,1,32,2,2.0,0.0,2500,5,3.0,2,2,3,1.0,NaN,1.0,NaN,NaN
86,1,40,1,2.0,0.0,2500,3,4.0,3,2,3,1.0,NaN,1.0,NaN,NaN
87,1,31,1,4.0,1.0,3500,4,4.0,3,3,3,1.0,NaN,1.0,NaN,NaN
88,1,28,1,4.0,0.0,4600,4,3.0,2,4,2,1.0,NaN,NaN,NaN,NaN
89,1,29,1,4.0,0.0,3900,4,3.0,3,4,3,1.0,NaN,NaN,NaN,NaN
90,2,31,2,2.0,0.0,2400,4,3.0,2,2,3,1.0,NaN,1.0,NaN,NaN